name: Deploy to PebbleHost
on:
  push:
    branches:
      - main  # Can change to current branch


jobs:
  sftp-deploy:
    name: Sync Files via SFTP
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    
    - name: Sync SFTP Folder
      uses: wlixcc/SFTP-Deploy-Action@v1.2.6
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PWD }}
        port: 2222  # pebblehost port
        local_path: './datapacks/'  #Grab only datapacks folder
        remote_path: '/world/datapacks'  # Target folder on PebbleHost
        sftp_only: true